
logging:
  config: classpath:logback-spring.xml
spring:
  datasource:
    druid:
      db1:
        username: sa
        password: 
        driver-class-name: org.h2.Driver
        url: jdbc:h2:tcp://127.0.0.1:9092/ez
        initialSize: 5
        minIdle: 5
        maxActive: 20
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
    active: jdbc
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB #单个数据大小
      max-request-size: 100MB #总数据大小
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
system:
  uploadType: OSS
  ossEndpoint: http://oss-cn-shanghai.aliyuncs.com
  imgEndpoint: imageseg.cn-shanghai.aliyuncs.com
  ossAccessKeyId: 
  ossAccessKeySecret: 
  ossBucketName: topezadmin
#h2Server: '-web,-tcpAllowOthers,-webAllowOthers,-tcp,-ifNotExists,-baseDir,'
topezadmin:
  # 默认true 开发时配置为false
  cacheFlag: false
  password: 
  # 默认dataSource springboot中配置的名字，如果有多个，逗号隔开
  datasourceBeanNames: 'dataSource'
  uploadPath: /data/upload
  downloadUrl: /core/downloadDesc.html?fileId=
  uploadUrl: /system/upload.html
  # 1000 打印完整SQL日志
  logType: 1000-10000
  adminStyle: layui
  indexUrl: /blog/index.html
  signoutUrl: /login/signout.html
  # 配置生成文件的绝对路径， 系统会监听文件改动，来自动更新配置
  navUrl: /laynavs.html
  holiday: '[["2024-1-1","2024-2-8","2024-2-9","2024-2-10","2024-2-11","2024-2-12","2024-2-13","2024-2-14","2024-2-15","2024-2-16","2024-2-17","2024-2-18","2024-2-19","2024-4-4","2024-4-5","2024-4-6","2024-5-1","2024-5-2","2024-5-3","2024-5-4","2024-5-5","2024-6-8","2024-6-9","2024-6-10","2024-9-15","2024-9-16","2024-9-17","2024-10-1","2024-10-2","2024-10-3","2024-10-4","2024-10-5","2024-10-6","2024-10-7"],["2024-2-4","2023-2-18","2024-4-7","2024-4-28","2024-5-11","2024-9-14","2024-9-29","2024-10-12"]]'
