package top.ezadmin.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.ezadmin.domain.model.BaseRegistration;
import top.ezadmin.domain.model.BaseRegistrationExample;

public interface BaseRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    long countByExample(BaseRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int deleteByExample(BaseRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int deleteByPrimaryKey(Long registrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int insert(BaseRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int insertSelective(BaseRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    List<BaseRegistration> selectByExample(BaseRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    BaseRegistration selectByPrimaryKey(Long registrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int updateByExampleSelective(@Param("record") BaseRegistration record, @Param("example") BaseRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int updateByExample(@Param("record") BaseRegistration record, @Param("example") BaseRegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int updateByPrimaryKeySelective(BaseRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_REGISTRATION
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    int updateByPrimaryKey(BaseRegistration record);
}