package top.ezadmin.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.ezadmin.domain.model.BaseTraderFinance;
import top.ezadmin.domain.model.BaseTraderFinanceExample;

public interface BaseTraderFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    long countByExample(BaseTraderFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int deleteByExample(BaseTraderFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int deleteByPrimaryKey(Integer traderFinanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int insert(BaseTraderFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int insertSelective(BaseTraderFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    List<BaseTraderFinance> selectByExample(BaseTraderFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    BaseTraderFinance selectByPrimaryKey(Integer traderFinanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByExampleSelective(@Param("record") BaseTraderFinance record, @Param("example") BaseTraderFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByExample(@Param("record") BaseTraderFinance record, @Param("example") BaseTraderFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByPrimaryKeySelective(BaseTraderFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASE_TRADER_FINANCE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByPrimaryKey(BaseTraderFinance record);
}