package top.ezadmin.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.ezadmin.domain.model.BlogCategory;
import top.ezadmin.domain.model.BlogCategoryExample;

public interface BlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    long countByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int deleteByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int insert(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int insertSelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    List<BlogCategory> selectByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    BlogCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int updateByExampleSelective(@Param("record") BlogCategory record, @Param("example") BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int updateByExample(@Param("record") BlogCategory record, @Param("example") BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int updateByPrimaryKeySelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BLOG_CATEGORY
     *
     * @mbg.generated Mon Oct 07 20:25:57 CST 2024
     */
    int updateByPrimaryKey(BlogCategory record);
}