package top.ezadmin.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.ezadmin.domain.model.CoreFile;
import top.ezadmin.domain.model.CoreFileExample;

public interface CoreFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    long countByExample(CoreFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int deleteByExample(CoreFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int deleteByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int insert(CoreFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int insertSelective(CoreFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    List<CoreFile> selectByExample(CoreFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    CoreFile selectByPrimaryKey(Long fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByExampleSelective(@Param("record") CoreFile record, @Param("example") CoreFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByExample(@Param("record") CoreFile record, @Param("example") CoreFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByPrimaryKeySelective(CoreFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CORE_FILE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByPrimaryKey(CoreFile record);
}