package top.ezadmin.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.ezadmin.domain.model.SaleorderGoods;
import top.ezadmin.domain.model.SaleorderGoodsExample;

public interface SaleorderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    long countByExample(SaleorderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int deleteByExample(SaleorderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int deleteByPrimaryKey(Long saleorderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int insert(SaleorderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int insertSelective(SaleorderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    List<SaleorderGoods> selectByExample(SaleorderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    SaleorderGoods selectByPrimaryKey(Long saleorderGoodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int updateByExampleSelective(@Param("record") SaleorderGoods record, @Param("example") SaleorderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int updateByExample(@Param("record") SaleorderGoods record, @Param("example") SaleorderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int updateByPrimaryKeySelective(SaleorderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    int updateByPrimaryKey(SaleorderGoods record);
}