package top.ezadmin.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.ezadmin.domain.model.SysUserRole;
import top.ezadmin.domain.model.SysUserRoleExample;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    long countByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int deleteByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int deleteByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int insertSelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    List<SysUserRole> selectByExample(SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    SysUserRole selectByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByExampleSelective(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByExample(@Param("record") SysUserRole record, @Param("example") SysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByPrimaryKeySelective(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_USER_ROLE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    int updateByPrimaryKey(SysUserRole record);
}