package top.ezadmin.domain.mapper;

import top.ezadmin.blog.model.VisitorLog;
import top.ezadmin.blog.model.VisitorLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VisitorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int countByExample(VisitorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int deleteByExample(VisitorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int insert(VisitorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int insertSelective(VisitorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    List<VisitorLog> selectByExample(VisitorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    VisitorLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") VisitorLog record, @Param("example") VisitorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int updateByExample(@Param("record") VisitorLog record, @Param("example") VisitorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int updateByPrimaryKeySelective(VisitorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VISITOR_LOG
     *
     * @mbggenerated Fri Apr 22 10:19:56 CST 2022
     */
    int updateByPrimaryKey(VisitorLog record);
}