package top.ezadmin.blog.model;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.BLOG_ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.BLOG_TITLE
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.BLOG_CONTENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String blogContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.ADD_TIME
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.VIEW_TIMES
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer viewTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.STATUS
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.CATEGORY_ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.LIKE_TIMES
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer likeTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.BLOG_SUB_TITLE
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String blogSubTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG.ENABLE_COMMENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer enableComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.BLOG_ID
     *
     * @return the value of T_BLOG.BLOG_ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.BLOG_ID
     *
     * @param blogId the value for T_BLOG.BLOG_ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.BLOG_TITLE
     *
     * @return the value of T_BLOG.BLOG_TITLE
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.BLOG_TITLE
     *
     * @param blogTitle the value for T_BLOG.BLOG_TITLE
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.BLOG_CONTENT
     *
     * @return the value of T_BLOG.BLOG_CONTENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.BLOG_CONTENT
     *
     * @param blogContent the value for T_BLOG.BLOG_CONTENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.ADD_TIME
     *
     * @return the value of T_BLOG.ADD_TIME
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.ADD_TIME
     *
     * @param addTime the value for T_BLOG.ADD_TIME
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.VIEW_TIMES
     *
     * @return the value of T_BLOG.VIEW_TIMES
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getViewTimes() {
        return viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.VIEW_TIMES
     *
     * @param viewTimes the value for T_BLOG.VIEW_TIMES
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setViewTimes(Integer viewTimes) {
        this.viewTimes = viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.STATUS
     *
     * @return the value of T_BLOG.STATUS
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.STATUS
     *
     * @param status the value for T_BLOG.STATUS
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.CATEGORY_ID
     *
     * @return the value of T_BLOG.CATEGORY_ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.CATEGORY_ID
     *
     * @param categoryId the value for T_BLOG.CATEGORY_ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.LIKE_TIMES
     *
     * @return the value of T_BLOG.LIKE_TIMES
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getLikeTimes() {
        return likeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.LIKE_TIMES
     *
     * @param likeTimes the value for T_BLOG.LIKE_TIMES
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setLikeTimes(Integer likeTimes) {
        this.likeTimes = likeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.BLOG_SUB_TITLE
     *
     * @return the value of T_BLOG.BLOG_SUB_TITLE
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getBlogSubTitle() {
        return blogSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.BLOG_SUB_TITLE
     *
     * @param blogSubTitle the value for T_BLOG.BLOG_SUB_TITLE
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setBlogSubTitle(String blogSubTitle) {
        this.blogSubTitle = blogSubTitle == null ? null : blogSubTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG.ENABLE_COMMENT
     *
     * @return the value of T_BLOG.ENABLE_COMMENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getEnableComment() {
        return enableComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG.ENABLE_COMMENT
     *
     * @param enableComment the value for T_BLOG.ENABLE_COMMENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setEnableComment(Integer enableComment) {
        this.enableComment = enableComment;
    }
}