package top.ezadmin.blog.model;

import java.util.Date;

public class VisitorLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VISITOR_LOG.ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VISITOR_LOG.VT_IP
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String vtIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VISITOR_LOG.VT_URL
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String vtUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VISITOR_LOG.ADD_TIME
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VISITOR_LOG.USER_AGENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VISITOR_LOG.SID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    private String sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VISITOR_LOG.ID
     *
     * @return the value of T_VISITOR_LOG.ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VISITOR_LOG.ID
     *
     * @param id the value for T_VISITOR_LOG.ID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VISITOR_LOG.VT_IP
     *
     * @return the value of T_VISITOR_LOG.VT_IP
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getVtIp() {
        return vtIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VISITOR_LOG.VT_IP
     *
     * @param vtIp the value for T_VISITOR_LOG.VT_IP
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setVtIp(String vtIp) {
        this.vtIp = vtIp == null ? null : vtIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VISITOR_LOG.VT_URL
     *
     * @return the value of T_VISITOR_LOG.VT_URL
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getVtUrl() {
        return vtUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VISITOR_LOG.VT_URL
     *
     * @param vtUrl the value for T_VISITOR_LOG.VT_URL
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setVtUrl(String vtUrl) {
        this.vtUrl = vtUrl == null ? null : vtUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VISITOR_LOG.ADD_TIME
     *
     * @return the value of T_VISITOR_LOG.ADD_TIME
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VISITOR_LOG.ADD_TIME
     *
     * @param addTime the value for T_VISITOR_LOG.ADD_TIME
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VISITOR_LOG.USER_AGENT
     *
     * @return the value of T_VISITOR_LOG.USER_AGENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VISITOR_LOG.USER_AGENT
     *
     * @param userAgent the value for T_VISITOR_LOG.USER_AGENT
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VISITOR_LOG.SID
     *
     * @return the value of T_VISITOR_LOG.SID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VISITOR_LOG.SID
     *
     * @param sid the value for T_VISITOR_LOG.SID
     *
     * @mbggenerated Sun Mar 27 17:10:57 CST 2022
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }
}