server:
  port: 8090
spring:
  application:
    name: mcp
  datasource:
    url: jdbc:mysql://192.168.2.54/QA_NEW_ERP_VEDENG_COM?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: fatwrite
    password: fatwrite
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    provider: ollama # 可选值: ollama, openai
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:8b
          temperature: 0
          stream: false
          max-tokens: 10000
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key:
      chat:
        options:
          model: qwen3-max
          temperature: 0
          stream: false
          max-tokens: 5000
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8181

logging:
  level:
    root: info
topezadmin:
  # 默认true 开发时配置为false
  cacheFlag: false
  password: 01ER4F6#$1ab3Hef
  # 默认dataSource springboot中配置的名字，如果有多个，逗号隔开
  datasourceBeanNames: 'dataSource'
  uploadPath: /Users/hp/data/upload
  downloadUrl: /core/downloadDesc.html?fileId=
  uploadUrl: /system/upload.html
  # 1000 打印完整SQL日志
  logType: 0000-10000
  adminStyle: layui
  clearUrl: /topezadmin/clearCache.html
  signoutUrl: /login/signout.html
  indexUrl: /doc/index.html
  # 配置生成文件的绝对路径， 系统会监听文件改动，来自动更新配置
  navUrl: /laynavs.html