package top.ezadmin.domain.model;

import java.util.Date;

public class BaseTraderAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.TRADER_ADDRESS_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Long traderAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.TRADER_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Long traderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.ADDRESS_TYPE
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Integer addressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.REGION_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.PROVICE_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String proviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.CITY_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.TRADER_ADDRESS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String traderAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.ADD_TIME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.ADD_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Long addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.ADD_NAME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String addName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.UPDATE_TIME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.UPDATE_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.UPDATE_NAME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.DELETE_FLAG
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Byte deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.COMMENT
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.COMPANY_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_TRADER_ADDRESS.STATUS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.TRADER_ADDRESS_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.TRADER_ADDRESS_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Long getTraderAddressId() {
        return traderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.TRADER_ADDRESS_ID
     *
     * @param traderAddressId the value for T_BASE_TRADER_ADDRESS.TRADER_ADDRESS_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setTraderAddressId(Long traderAddressId) {
        this.traderAddressId = traderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.TRADER_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.TRADER_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Long getTraderId() {
        return traderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.TRADER_ID
     *
     * @param traderId the value for T_BASE_TRADER_ADDRESS.TRADER_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setTraderId(Long traderId) {
        this.traderId = traderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.ADDRESS_TYPE
     *
     * @return the value of T_BASE_TRADER_ADDRESS.ADDRESS_TYPE
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Integer getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.ADDRESS_TYPE
     *
     * @param addressType the value for T_BASE_TRADER_ADDRESS.ADDRESS_TYPE
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setAddressType(Integer addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.REGION_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.REGION_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.REGION_ID
     *
     * @param regionId the value for T_BASE_TRADER_ADDRESS.REGION_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.PROVICE_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.PROVICE_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getProviceId() {
        return proviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.PROVICE_ID
     *
     * @param proviceId the value for T_BASE_TRADER_ADDRESS.PROVICE_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setProviceId(String proviceId) {
        this.proviceId = proviceId == null ? null : proviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.CITY_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.CITY_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.CITY_ID
     *
     * @param cityId the value for T_BASE_TRADER_ADDRESS.CITY_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.TRADER_ADDRESS
     *
     * @return the value of T_BASE_TRADER_ADDRESS.TRADER_ADDRESS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getTraderAddress() {
        return traderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.TRADER_ADDRESS
     *
     * @param traderAddress the value for T_BASE_TRADER_ADDRESS.TRADER_ADDRESS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setTraderAddress(String traderAddress) {
        this.traderAddress = traderAddress == null ? null : traderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.ADD_TIME
     *
     * @return the value of T_BASE_TRADER_ADDRESS.ADD_TIME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.ADD_TIME
     *
     * @param addTime the value for T_BASE_TRADER_ADDRESS.ADD_TIME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.ADD_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.ADD_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.ADD_ID
     *
     * @param addId the value for T_BASE_TRADER_ADDRESS.ADD_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.ADD_NAME
     *
     * @return the value of T_BASE_TRADER_ADDRESS.ADD_NAME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.ADD_NAME
     *
     * @param addName the value for T_BASE_TRADER_ADDRESS.ADD_NAME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.UPDATE_TIME
     *
     * @return the value of T_BASE_TRADER_ADDRESS.UPDATE_TIME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.UPDATE_TIME
     *
     * @param updateTime the value for T_BASE_TRADER_ADDRESS.UPDATE_TIME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.UPDATE_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.UPDATE_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.UPDATE_ID
     *
     * @param updateId the value for T_BASE_TRADER_ADDRESS.UPDATE_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.UPDATE_NAME
     *
     * @return the value of T_BASE_TRADER_ADDRESS.UPDATE_NAME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.UPDATE_NAME
     *
     * @param updateName the value for T_BASE_TRADER_ADDRESS.UPDATE_NAME
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.DELETE_FLAG
     *
     * @return the value of T_BASE_TRADER_ADDRESS.DELETE_FLAG
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.DELETE_FLAG
     *
     * @param deleteFlag the value for T_BASE_TRADER_ADDRESS.DELETE_FLAG
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.COMMENT
     *
     * @return the value of T_BASE_TRADER_ADDRESS.COMMENT
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.COMMENT
     *
     * @param comment the value for T_BASE_TRADER_ADDRESS.COMMENT
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.COMPANY_ID
     *
     * @return the value of T_BASE_TRADER_ADDRESS.COMPANY_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.COMPANY_ID
     *
     * @param companyId the value for T_BASE_TRADER_ADDRESS.COMPANY_ID
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_TRADER_ADDRESS.STATUS
     *
     * @return the value of T_BASE_TRADER_ADDRESS.STATUS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_TRADER_ADDRESS.STATUS
     *
     * @param status the value for T_BASE_TRADER_ADDRESS.STATUS
     *
     * @mbg.generated Sat Dec 07 21:30:29 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}