package top.ezadmin.domain.model;

import java.util.Date;

public class BaseSupplierAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long supplierAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.ADDRESS_TYPE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer addressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.REGION_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.PROVICE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String proviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.CITY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String supplierAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String addName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Byte deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.COMMENT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_ADDRESS.STATUS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getSupplierAddressId() {
        return supplierAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS_ID
     *
     * @param supplierAddressId the value for T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setSupplierAddressId(Long supplierAddressId) {
        this.supplierAddressId = supplierAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ID
     *
     * @param supplierId the value for T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.ADDRESS_TYPE
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.ADDRESS_TYPE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.ADDRESS_TYPE
     *
     * @param addressType the value for T_BASE_SUPPLIER_ADDRESS.ADDRESS_TYPE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddressType(Integer addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.REGION_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.REGION_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.REGION_ID
     *
     * @param regionId the value for T_BASE_SUPPLIER_ADDRESS.REGION_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.PROVICE_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.PROVICE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getProviceId() {
        return proviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.PROVICE_ID
     *
     * @param proviceId the value for T_BASE_SUPPLIER_ADDRESS.PROVICE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setProviceId(String proviceId) {
        this.proviceId = proviceId == null ? null : proviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.CITY_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.CITY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.CITY_ID
     *
     * @param cityId the value for T_BASE_SUPPLIER_ADDRESS.CITY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS
     *
     * @param supplierAddress the value for T_BASE_SUPPLIER_ADDRESS.SUPPLIER_ADDRESS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress == null ? null : supplierAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.ADD_TIME
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.ADD_TIME
     *
     * @param addTime the value for T_BASE_SUPPLIER_ADDRESS.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.ADD_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.ADD_ID
     *
     * @param addId the value for T_BASE_SUPPLIER_ADDRESS.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.ADD_NAME
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.ADD_NAME
     *
     * @param addName the value for T_BASE_SUPPLIER_ADDRESS.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_TIME
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_TIME
     *
     * @param updateTime the value for T_BASE_SUPPLIER_ADDRESS.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_ID
     *
     * @param updateId the value for T_BASE_SUPPLIER_ADDRESS.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_NAME
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.UPDATE_NAME
     *
     * @param updateName the value for T_BASE_SUPPLIER_ADDRESS.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.DELETE_FLAG
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.DELETE_FLAG
     *
     * @param deleteFlag the value for T_BASE_SUPPLIER_ADDRESS.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.COMMENT
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.COMMENT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.COMMENT
     *
     * @param comment the value for T_BASE_SUPPLIER_ADDRESS.COMMENT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.COMPANY_ID
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.COMPANY_ID
     *
     * @param companyId the value for T_BASE_SUPPLIER_ADDRESS.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_ADDRESS.STATUS
     *
     * @return the value of T_BASE_SUPPLIER_ADDRESS.STATUS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_ADDRESS.STATUS
     *
     * @param status the value for T_BASE_SUPPLIER_ADDRESS.STATUS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}