package top.ezadmin.domain.model;

import java.util.Date;

public class BaseBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.BRAND_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.BRAND_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.BRAND_NAME_EN
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String brandNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.BRAND_WEBSITE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String brandWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String addName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Byte deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.DISPLAY_ORDER
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_BRAND.KEYWORDS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String keywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.BRAND_ID
     *
     * @return the value of T_BASE_BRAND.BRAND_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.BRAND_ID
     *
     * @param brandId the value for T_BASE_BRAND.BRAND_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.COMPANY_ID
     *
     * @return the value of T_BASE_BRAND.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.COMPANY_ID
     *
     * @param companyId the value for T_BASE_BRAND.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.BRAND_NAME
     *
     * @return the value of T_BASE_BRAND.BRAND_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.BRAND_NAME
     *
     * @param brandName the value for T_BASE_BRAND.BRAND_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.BRAND_NAME_EN
     *
     * @return the value of T_BASE_BRAND.BRAND_NAME_EN
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getBrandNameEn() {
        return brandNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.BRAND_NAME_EN
     *
     * @param brandNameEn the value for T_BASE_BRAND.BRAND_NAME_EN
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBrandNameEn(String brandNameEn) {
        this.brandNameEn = brandNameEn == null ? null : brandNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.BRAND_WEBSITE
     *
     * @return the value of T_BASE_BRAND.BRAND_WEBSITE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getBrandWebsite() {
        return brandWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.BRAND_WEBSITE
     *
     * @param brandWebsite the value for T_BASE_BRAND.BRAND_WEBSITE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBrandWebsite(String brandWebsite) {
        this.brandWebsite = brandWebsite == null ? null : brandWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.ADD_TIME
     *
     * @return the value of T_BASE_BRAND.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.ADD_TIME
     *
     * @param addTime the value for T_BASE_BRAND.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.ADD_ID
     *
     * @return the value of T_BASE_BRAND.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.ADD_ID
     *
     * @param addId the value for T_BASE_BRAND.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.ADD_NAME
     *
     * @return the value of T_BASE_BRAND.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.ADD_NAME
     *
     * @param addName the value for T_BASE_BRAND.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.UPDATE_TIME
     *
     * @return the value of T_BASE_BRAND.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.UPDATE_TIME
     *
     * @param updateTime the value for T_BASE_BRAND.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.UPDATE_ID
     *
     * @return the value of T_BASE_BRAND.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.UPDATE_ID
     *
     * @param updateId the value for T_BASE_BRAND.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.UPDATE_NAME
     *
     * @return the value of T_BASE_BRAND.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.UPDATE_NAME
     *
     * @param updateName the value for T_BASE_BRAND.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.DELETE_FLAG
     *
     * @return the value of T_BASE_BRAND.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.DELETE_FLAG
     *
     * @param deleteFlag the value for T_BASE_BRAND.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.DISPLAY_ORDER
     *
     * @return the value of T_BASE_BRAND.DISPLAY_ORDER
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.DISPLAY_ORDER
     *
     * @param displayOrder the value for T_BASE_BRAND.DISPLAY_ORDER
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_BRAND.KEYWORDS
     *
     * @return the value of T_BASE_BRAND.KEYWORDS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_BRAND.KEYWORDS
     *
     * @param keywords the value for T_BASE_BRAND.KEYWORDS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }
}