package top.ezadmin.domain.model;

import java.util.Date;

public class BaseManufacturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.MANUFACTURER_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Long manufacturerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.MANUFACTURER_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String manufacturerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.ADD_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.ADD_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String addName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.ADD_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Long addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.UPDATE_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.UPDATE_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.UPDATE_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.BC_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String bcFileIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.BC_ISSUE_DATE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date bcIssueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.BC_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date bcStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.BC_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date bcEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PE_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String peFileIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PRODUCT_COMPANY_LICENCE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String productCompanyLicence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PE_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date peStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PE_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date peEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.RC_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String rcFileIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.RC_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date rcStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.RC_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date rcEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.RECORD_CERTIFICATE_LICENCE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String recordCertificateLicence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PEP_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private String pepFileIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PEP_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date pepStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.PEP_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Date pepEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.CHECK_STATUS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Integer checkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_MANUFACTURER.COMPANY_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.MANUFACTURER_ID
     *
     * @return the value of T_BASE_MANUFACTURER.MANUFACTURER_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Long getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.MANUFACTURER_ID
     *
     * @param manufacturerId the value for T_BASE_MANUFACTURER.MANUFACTURER_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setManufacturerId(Long manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.MANUFACTURER_NAME
     *
     * @return the value of T_BASE_MANUFACTURER.MANUFACTURER_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.MANUFACTURER_NAME
     *
     * @param manufacturerName the value for T_BASE_MANUFACTURER.MANUFACTURER_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName == null ? null : manufacturerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.DELETE_FLAG
     *
     * @return the value of T_BASE_MANUFACTURER.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.DELETE_FLAG
     *
     * @param deleteFlag the value for T_BASE_MANUFACTURER.DELETE_FLAG
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.ADD_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.ADD_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.ADD_TIME
     *
     * @param addTime the value for T_BASE_MANUFACTURER.ADD_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.ADD_NAME
     *
     * @return the value of T_BASE_MANUFACTURER.ADD_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.ADD_NAME
     *
     * @param addName the value for T_BASE_MANUFACTURER.ADD_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.ADD_ID
     *
     * @return the value of T_BASE_MANUFACTURER.ADD_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.ADD_ID
     *
     * @param addId the value for T_BASE_MANUFACTURER.ADD_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.UPDATE_ID
     *
     * @return the value of T_BASE_MANUFACTURER.UPDATE_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.UPDATE_ID
     *
     * @param updateId the value for T_BASE_MANUFACTURER.UPDATE_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.UPDATE_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.UPDATE_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.UPDATE_TIME
     *
     * @param updateTime the value for T_BASE_MANUFACTURER.UPDATE_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.UPDATE_NAME
     *
     * @return the value of T_BASE_MANUFACTURER.UPDATE_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.UPDATE_NAME
     *
     * @param updateName the value for T_BASE_MANUFACTURER.UPDATE_NAME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.BC_FILE_IDS
     *
     * @return the value of T_BASE_MANUFACTURER.BC_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getBcFileIds() {
        return bcFileIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.BC_FILE_IDS
     *
     * @param bcFileIds the value for T_BASE_MANUFACTURER.BC_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setBcFileIds(String bcFileIds) {
        this.bcFileIds = bcFileIds == null ? null : bcFileIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.BC_ISSUE_DATE
     *
     * @return the value of T_BASE_MANUFACTURER.BC_ISSUE_DATE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getBcIssueDate() {
        return bcIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.BC_ISSUE_DATE
     *
     * @param bcIssueDate the value for T_BASE_MANUFACTURER.BC_ISSUE_DATE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setBcIssueDate(Date bcIssueDate) {
        this.bcIssueDate = bcIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.BC_START_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.BC_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getBcStartTime() {
        return bcStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.BC_START_TIME
     *
     * @param bcStartTime the value for T_BASE_MANUFACTURER.BC_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setBcStartTime(Date bcStartTime) {
        this.bcStartTime = bcStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.BC_END_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.BC_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getBcEndTime() {
        return bcEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.BC_END_TIME
     *
     * @param bcEndTime the value for T_BASE_MANUFACTURER.BC_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setBcEndTime(Date bcEndTime) {
        this.bcEndTime = bcEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PE_FILE_IDS
     *
     * @return the value of T_BASE_MANUFACTURER.PE_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getPeFileIds() {
        return peFileIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PE_FILE_IDS
     *
     * @param peFileIds the value for T_BASE_MANUFACTURER.PE_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setPeFileIds(String peFileIds) {
        this.peFileIds = peFileIds == null ? null : peFileIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PRODUCT_COMPANY_LICENCE
     *
     * @return the value of T_BASE_MANUFACTURER.PRODUCT_COMPANY_LICENCE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getProductCompanyLicence() {
        return productCompanyLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PRODUCT_COMPANY_LICENCE
     *
     * @param productCompanyLicence the value for T_BASE_MANUFACTURER.PRODUCT_COMPANY_LICENCE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setProductCompanyLicence(String productCompanyLicence) {
        this.productCompanyLicence = productCompanyLicence == null ? null : productCompanyLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PE_START_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.PE_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getPeStartTime() {
        return peStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PE_START_TIME
     *
     * @param peStartTime the value for T_BASE_MANUFACTURER.PE_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setPeStartTime(Date peStartTime) {
        this.peStartTime = peStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PE_END_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.PE_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getPeEndTime() {
        return peEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PE_END_TIME
     *
     * @param peEndTime the value for T_BASE_MANUFACTURER.PE_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setPeEndTime(Date peEndTime) {
        this.peEndTime = peEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.RC_FILE_IDS
     *
     * @return the value of T_BASE_MANUFACTURER.RC_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getRcFileIds() {
        return rcFileIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.RC_FILE_IDS
     *
     * @param rcFileIds the value for T_BASE_MANUFACTURER.RC_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setRcFileIds(String rcFileIds) {
        this.rcFileIds = rcFileIds == null ? null : rcFileIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.RC_START_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.RC_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getRcStartTime() {
        return rcStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.RC_START_TIME
     *
     * @param rcStartTime the value for T_BASE_MANUFACTURER.RC_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setRcStartTime(Date rcStartTime) {
        this.rcStartTime = rcStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.RC_END_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.RC_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getRcEndTime() {
        return rcEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.RC_END_TIME
     *
     * @param rcEndTime the value for T_BASE_MANUFACTURER.RC_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setRcEndTime(Date rcEndTime) {
        this.rcEndTime = rcEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.RECORD_CERTIFICATE_LICENCE
     *
     * @return the value of T_BASE_MANUFACTURER.RECORD_CERTIFICATE_LICENCE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getRecordCertificateLicence() {
        return recordCertificateLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.RECORD_CERTIFICATE_LICENCE
     *
     * @param recordCertificateLicence the value for T_BASE_MANUFACTURER.RECORD_CERTIFICATE_LICENCE
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setRecordCertificateLicence(String recordCertificateLicence) {
        this.recordCertificateLicence = recordCertificateLicence == null ? null : recordCertificateLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PEP_FILE_IDS
     *
     * @return the value of T_BASE_MANUFACTURER.PEP_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public String getPepFileIds() {
        return pepFileIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PEP_FILE_IDS
     *
     * @param pepFileIds the value for T_BASE_MANUFACTURER.PEP_FILE_IDS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setPepFileIds(String pepFileIds) {
        this.pepFileIds = pepFileIds == null ? null : pepFileIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PEP_START_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.PEP_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getPepStartTime() {
        return pepStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PEP_START_TIME
     *
     * @param pepStartTime the value for T_BASE_MANUFACTURER.PEP_START_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setPepStartTime(Date pepStartTime) {
        this.pepStartTime = pepStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.PEP_END_TIME
     *
     * @return the value of T_BASE_MANUFACTURER.PEP_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Date getPepEndTime() {
        return pepEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.PEP_END_TIME
     *
     * @param pepEndTime the value for T_BASE_MANUFACTURER.PEP_END_TIME
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setPepEndTime(Date pepEndTime) {
        this.pepEndTime = pepEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.CHECK_STATUS
     *
     * @return the value of T_BASE_MANUFACTURER.CHECK_STATUS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Integer getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.CHECK_STATUS
     *
     * @param checkStatus the value for T_BASE_MANUFACTURER.CHECK_STATUS
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_MANUFACTURER.COMPANY_ID
     *
     * @return the value of T_BASE_MANUFACTURER.COMPANY_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_MANUFACTURER.COMPANY_ID
     *
     * @param companyId the value for T_BASE_MANUFACTURER.COMPANY_ID
     *
     * @mbg.generated Tue Dec 24 14:18:04 CST 2024
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}