package top.ezadmin.domain.model;

public class BaseSupplierFinance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_FINANCE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer supplierFinanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_TYPE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Byte supplierType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.CREDIT_RATING
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer creditRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.REG_ADDRESS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String regAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.REG_TEL
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String regTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.TAX_NUM
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String taxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_DOMAIN
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String averageTaxpayerDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_URI
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String averageTaxpayerUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.BANK
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.BANK_CODE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String bankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.BANK_ACCOUNT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.COMMENTS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.CREATOR
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.MOD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long modTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASE_SUPPLIER_FINANCE.UPDATER
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_FINANCE_ID
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.SUPPLIER_FINANCE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getSupplierFinanceId() {
        return supplierFinanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_FINANCE_ID
     *
     * @param supplierFinanceId the value for T_BASE_SUPPLIER_FINANCE.SUPPLIER_FINANCE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setSupplierFinanceId(Integer supplierFinanceId) {
        this.supplierFinanceId = supplierFinanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_ID
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.SUPPLIER_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_ID
     *
     * @param supplierId the value for T_BASE_SUPPLIER_FINANCE.SUPPLIER_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_TYPE
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.SUPPLIER_TYPE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Byte getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.SUPPLIER_TYPE
     *
     * @param supplierType the value for T_BASE_SUPPLIER_FINANCE.SUPPLIER_TYPE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setSupplierType(Byte supplierType) {
        this.supplierType = supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.CREDIT_RATING
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.CREDIT_RATING
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getCreditRating() {
        return creditRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.CREDIT_RATING
     *
     * @param creditRating the value for T_BASE_SUPPLIER_FINANCE.CREDIT_RATING
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setCreditRating(Integer creditRating) {
        this.creditRating = creditRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.REG_ADDRESS
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.REG_ADDRESS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getRegAddress() {
        return regAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.REG_ADDRESS
     *
     * @param regAddress the value for T_BASE_SUPPLIER_FINANCE.REG_ADDRESS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRegAddress(String regAddress) {
        this.regAddress = regAddress == null ? null : regAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.REG_TEL
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.REG_TEL
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getRegTel() {
        return regTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.REG_TEL
     *
     * @param regTel the value for T_BASE_SUPPLIER_FINANCE.REG_TEL
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRegTel(String regTel) {
        this.regTel = regTel == null ? null : regTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.TAX_NUM
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.TAX_NUM
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getTaxNum() {
        return taxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.TAX_NUM
     *
     * @param taxNum the value for T_BASE_SUPPLIER_FINANCE.TAX_NUM
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setTaxNum(String taxNum) {
        this.taxNum = taxNum == null ? null : taxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_DOMAIN
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_DOMAIN
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getAverageTaxpayerDomain() {
        return averageTaxpayerDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_DOMAIN
     *
     * @param averageTaxpayerDomain the value for T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_DOMAIN
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAverageTaxpayerDomain(String averageTaxpayerDomain) {
        this.averageTaxpayerDomain = averageTaxpayerDomain == null ? null : averageTaxpayerDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_URI
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_URI
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getAverageTaxpayerUri() {
        return averageTaxpayerUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_URI
     *
     * @param averageTaxpayerUri the value for T_BASE_SUPPLIER_FINANCE.AVERAGE_TAXPAYER_URI
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAverageTaxpayerUri(String averageTaxpayerUri) {
        this.averageTaxpayerUri = averageTaxpayerUri == null ? null : averageTaxpayerUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.BANK
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.BANK
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.BANK
     *
     * @param bank the value for T_BASE_SUPPLIER_FINANCE.BANK
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.BANK_CODE
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.BANK_CODE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.BANK_CODE
     *
     * @param bankCode the value for T_BASE_SUPPLIER_FINANCE.BANK_CODE
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.BANK_ACCOUNT
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.BANK_ACCOUNT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.BANK_ACCOUNT
     *
     * @param bankAccount the value for T_BASE_SUPPLIER_FINANCE.BANK_ACCOUNT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.COMMENTS
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.COMMENTS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.COMMENTS
     *
     * @param comments the value for T_BASE_SUPPLIER_FINANCE.COMMENTS
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.ADD_TIME
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.ADD_TIME
     *
     * @param addTime the value for T_BASE_SUPPLIER_FINANCE.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.CREATOR
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.CREATOR
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.CREATOR
     *
     * @param creator the value for T_BASE_SUPPLIER_FINANCE.CREATOR
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.MOD_TIME
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.MOD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.MOD_TIME
     *
     * @param modTime the value for T_BASE_SUPPLIER_FINANCE.MOD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setModTime(Long modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASE_SUPPLIER_FINANCE.UPDATER
     *
     * @return the value of T_BASE_SUPPLIER_FINANCE.UPDATER
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASE_SUPPLIER_FINANCE.UPDATER
     *
     * @param updater the value for T_BASE_SUPPLIER_FINANCE.UPDATER
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }
}