package top.ezadmin.domain.model;

import java.util.Date;

public class BlogMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.USER_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.USER_EMAIL
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.BLOG_MESSAGE
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private String blogMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.ADD_IP
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private String addIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.BLOG_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.ON_LINE
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Integer onLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.ADD_TIME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.ADD_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Long addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.ADD_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private String addName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.UPDATE_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.UPDATE_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOG_MESSAGE.DELETE_FLAG
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.ID
     *
     * @return the value of T_BLOG_MESSAGE.ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.ID
     *
     * @param id the value for T_BLOG_MESSAGE.ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.USER_NAME
     *
     * @return the value of T_BLOG_MESSAGE.USER_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.USER_NAME
     *
     * @param userName the value for T_BLOG_MESSAGE.USER_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.USER_EMAIL
     *
     * @return the value of T_BLOG_MESSAGE.USER_EMAIL
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.USER_EMAIL
     *
     * @param userEmail the value for T_BLOG_MESSAGE.USER_EMAIL
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.BLOG_MESSAGE
     *
     * @return the value of T_BLOG_MESSAGE.BLOG_MESSAGE
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public String getBlogMessage() {
        return blogMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.BLOG_MESSAGE
     *
     * @param blogMessage the value for T_BLOG_MESSAGE.BLOG_MESSAGE
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setBlogMessage(String blogMessage) {
        this.blogMessage = blogMessage == null ? null : blogMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.ADD_IP
     *
     * @return the value of T_BLOG_MESSAGE.ADD_IP
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public String getAddIp() {
        return addIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.ADD_IP
     *
     * @param addIp the value for T_BLOG_MESSAGE.ADD_IP
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setAddIp(String addIp) {
        this.addIp = addIp == null ? null : addIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.BLOG_ID
     *
     * @return the value of T_BLOG_MESSAGE.BLOG_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.BLOG_ID
     *
     * @param blogId the value for T_BLOG_MESSAGE.BLOG_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.ON_LINE
     *
     * @return the value of T_BLOG_MESSAGE.ON_LINE
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Integer getOnLine() {
        return onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.ON_LINE
     *
     * @param onLine the value for T_BLOG_MESSAGE.ON_LINE
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setOnLine(Integer onLine) {
        this.onLine = onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.ADD_TIME
     *
     * @return the value of T_BLOG_MESSAGE.ADD_TIME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.ADD_TIME
     *
     * @param addTime the value for T_BLOG_MESSAGE.ADD_TIME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.ADD_ID
     *
     * @return the value of T_BLOG_MESSAGE.ADD_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.ADD_ID
     *
     * @param addId the value for T_BLOG_MESSAGE.ADD_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.ADD_NAME
     *
     * @return the value of T_BLOG_MESSAGE.ADD_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.ADD_NAME
     *
     * @param addName the value for T_BLOG_MESSAGE.ADD_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.UPDATE_TIME
     *
     * @return the value of T_BLOG_MESSAGE.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.UPDATE_TIME
     *
     * @param updateTime the value for T_BLOG_MESSAGE.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.UPDATE_ID
     *
     * @return the value of T_BLOG_MESSAGE.UPDATE_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.UPDATE_ID
     *
     * @param updateId the value for T_BLOG_MESSAGE.UPDATE_ID
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.UPDATE_NAME
     *
     * @return the value of T_BLOG_MESSAGE.UPDATE_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.UPDATE_NAME
     *
     * @param updateName the value for T_BLOG_MESSAGE.UPDATE_NAME
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOG_MESSAGE.DELETE_FLAG
     *
     * @return the value of T_BLOG_MESSAGE.DELETE_FLAG
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOG_MESSAGE.DELETE_FLAG
     *
     * @param deleteFlag the value for T_BLOG_MESSAGE.DELETE_FLAG
     *
     * @mbg.generated Thu Mar 28 13:51:24 CST 2024
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}