package top.ezadmin.domain.model;

import java.util.Date;

public class EzCloud {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.ID
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.EZ_CODE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private String ezCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.EZ_TYPE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private Integer ezType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.APP_NAME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.ADD_TIME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.IS_DEL
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.DATASOURCE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private String datasource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.EZ_NAME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private String ezName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ez_cloud.EZ_CONFIG
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    private String ezConfig;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.ID
     *
     * @return the value of t_ez_cloud.ID
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.ID
     *
     * @param id the value for t_ez_cloud.ID
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.EZ_CODE
     *
     * @return the value of t_ez_cloud.EZ_CODE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public String getEzCode() {
        return ezCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.EZ_CODE
     *
     * @param ezCode the value for t_ez_cloud.EZ_CODE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setEzCode(String ezCode) {
        this.ezCode = ezCode == null ? null : ezCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.EZ_TYPE
     *
     * @return the value of t_ez_cloud.EZ_TYPE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public Integer getEzType() {
        return ezType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.EZ_TYPE
     *
     * @param ezType the value for t_ez_cloud.EZ_TYPE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setEzType(Integer ezType) {
        this.ezType = ezType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.APP_NAME
     *
     * @return the value of t_ez_cloud.APP_NAME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.APP_NAME
     *
     * @param appName the value for t_ez_cloud.APP_NAME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.ADD_TIME
     *
     * @return the value of t_ez_cloud.ADD_TIME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.ADD_TIME
     *
     * @param addTime the value for t_ez_cloud.ADD_TIME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.UPDATE_TIME
     *
     * @return the value of t_ez_cloud.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.UPDATE_TIME
     *
     * @param updateTime the value for t_ez_cloud.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.IS_DEL
     *
     * @return the value of t_ez_cloud.IS_DEL
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.IS_DEL
     *
     * @param isDel the value for t_ez_cloud.IS_DEL
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.DATASOURCE
     *
     * @return the value of t_ez_cloud.DATASOURCE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.DATASOURCE
     *
     * @param datasource the value for t_ez_cloud.DATASOURCE
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.EZ_NAME
     *
     * @return the value of t_ez_cloud.EZ_NAME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public String getEzName() {
        return ezName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.EZ_NAME
     *
     * @param ezName the value for t_ez_cloud.EZ_NAME
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setEzName(String ezName) {
        this.ezName = ezName == null ? null : ezName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ez_cloud.EZ_CONFIG
     *
     * @return the value of t_ez_cloud.EZ_CONFIG
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public String getEzConfig() {
        return ezConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ez_cloud.EZ_CONFIG
     *
     * @param ezConfig the value for t_ez_cloud.EZ_CONFIG
     *
     * @mbg.generated Mon Jan 22 15:12:44 CST 2024
     */
    public void setEzConfig(String ezConfig) {
        this.ezConfig = ezConfig == null ? null : ezConfig.trim();
    }
}