package top.ezadmin.domain.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SaleorderGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public SaleorderGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSaleorderGoodsIdIsNull() {
            addCriterion("SALEORDER_GOODS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdIsNotNull() {
            addCriterion("SALEORDER_GOODS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdEqualTo(Long value) {
            addCriterion("SALEORDER_GOODS_ID =", value, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdNotEqualTo(Long value) {
            addCriterion("SALEORDER_GOODS_ID <>", value, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdGreaterThan(Long value) {
            addCriterion("SALEORDER_GOODS_ID >", value, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SALEORDER_GOODS_ID >=", value, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdLessThan(Long value) {
            addCriterion("SALEORDER_GOODS_ID <", value, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("SALEORDER_GOODS_ID <=", value, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdIn(List<Long> values) {
            addCriterion("SALEORDER_GOODS_ID in", values, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdNotIn(List<Long> values) {
            addCriterion("SALEORDER_GOODS_ID not in", values, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdBetween(Long value1, Long value2) {
            addCriterion("SALEORDER_GOODS_ID between", value1, value2, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("SALEORDER_GOODS_ID not between", value1, value2, "saleorderGoodsId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdIsNull() {
            addCriterion("SALEORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdIsNotNull() {
            addCriterion("SALEORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdEqualTo(Long value) {
            addCriterion("SALEORDER_ID =", value, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdNotEqualTo(Long value) {
            addCriterion("SALEORDER_ID <>", value, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdGreaterThan(Long value) {
            addCriterion("SALEORDER_ID >", value, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SALEORDER_ID >=", value, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdLessThan(Long value) {
            addCriterion("SALEORDER_ID <", value, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdLessThanOrEqualTo(Long value) {
            addCriterion("SALEORDER_ID <=", value, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdIn(List<Long> values) {
            addCriterion("SALEORDER_ID in", values, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdNotIn(List<Long> values) {
            addCriterion("SALEORDER_ID not in", values, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdBetween(Long value1, Long value2) {
            addCriterion("SALEORDER_ID between", value1, value2, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andSaleorderIdNotBetween(Long value1, Long value2) {
            addCriterion("SALEORDER_ID not between", value1, value2, "saleorderId");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("PROD_ID is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("PROD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(Long value) {
            addCriterion("PROD_ID =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(Long value) {
            addCriterion("PROD_ID <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(Long value) {
            addCriterion("PROD_ID >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROD_ID >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(Long value) {
            addCriterion("PROD_ID <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(Long value) {
            addCriterion("PROD_ID <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<Long> values) {
            addCriterion("PROD_ID in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<Long> values) {
            addCriterion("PROD_ID not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(Long value1, Long value2) {
            addCriterion("PROD_ID between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(Long value1, Long value2) {
            addCriterion("PROD_ID not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdCodeIsNull() {
            addCriterion("PROD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andProdCodeIsNotNull() {
            addCriterion("PROD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andProdCodeEqualTo(String value) {
            addCriterion("PROD_CODE =", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeNotEqualTo(String value) {
            addCriterion("PROD_CODE <>", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeGreaterThan(String value) {
            addCriterion("PROD_CODE >", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_CODE >=", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeLessThan(String value) {
            addCriterion("PROD_CODE <", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeLessThanOrEqualTo(String value) {
            addCriterion("PROD_CODE <=", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeLike(String value) {
            addCriterion("PROD_CODE like", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeNotLike(String value) {
            addCriterion("PROD_CODE not like", value, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeIn(List<String> values) {
            addCriterion("PROD_CODE in", values, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeNotIn(List<String> values) {
            addCriterion("PROD_CODE not in", values, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeBetween(String value1, String value2) {
            addCriterion("PROD_CODE between", value1, value2, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdCodeNotBetween(String value1, String value2) {
            addCriterion("PROD_CODE not between", value1, value2, "prodCode");
            return (Criteria) this;
        }

        public Criteria andProdNameIsNull() {
            addCriterion("PROD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andProdNameIsNotNull() {
            addCriterion("PROD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andProdNameEqualTo(String value) {
            addCriterion("PROD_NAME =", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotEqualTo(String value) {
            addCriterion("PROD_NAME <>", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameGreaterThan(String value) {
            addCriterion("PROD_NAME >", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_NAME >=", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLessThan(String value) {
            addCriterion("PROD_NAME <", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLessThanOrEqualTo(String value) {
            addCriterion("PROD_NAME <=", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameLike(String value) {
            addCriterion("PROD_NAME like", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotLike(String value) {
            addCriterion("PROD_NAME not like", value, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameIn(List<String> values) {
            addCriterion("PROD_NAME in", values, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotIn(List<String> values) {
            addCriterion("PROD_NAME not in", values, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameBetween(String value1, String value2) {
            addCriterion("PROD_NAME between", value1, value2, "prodName");
            return (Criteria) this;
        }

        public Criteria andProdNameNotBetween(String value1, String value2) {
            addCriterion("PROD_NAME not between", value1, value2, "prodName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("BRAND_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("BRAND_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("BRAND_NAME =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("BRAND_NAME <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("BRAND_NAME >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("BRAND_NAME >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("BRAND_NAME <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("BRAND_NAME <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("BRAND_NAME like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("BRAND_NAME not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("BRAND_NAME in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("BRAND_NAME not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("BRAND_NAME between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("BRAND_NAME not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecIsNull() {
            addCriterion("PROD_MODEL_SPEC is null");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecIsNotNull() {
            addCriterion("PROD_MODEL_SPEC is not null");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecEqualTo(String value) {
            addCriterion("PROD_MODEL_SPEC =", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecNotEqualTo(String value) {
            addCriterion("PROD_MODEL_SPEC <>", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecGreaterThan(String value) {
            addCriterion("PROD_MODEL_SPEC >", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_MODEL_SPEC >=", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecLessThan(String value) {
            addCriterion("PROD_MODEL_SPEC <", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecLessThanOrEqualTo(String value) {
            addCriterion("PROD_MODEL_SPEC <=", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecLike(String value) {
            addCriterion("PROD_MODEL_SPEC like", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecNotLike(String value) {
            addCriterion("PROD_MODEL_SPEC not like", value, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecIn(List<String> values) {
            addCriterion("PROD_MODEL_SPEC in", values, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecNotIn(List<String> values) {
            addCriterion("PROD_MODEL_SPEC not in", values, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecBetween(String value1, String value2) {
            addCriterion("PROD_MODEL_SPEC between", value1, value2, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andProdModelSpecNotBetween(String value1, String value2) {
            addCriterion("PROD_MODEL_SPEC not between", value1, value2, "prodModelSpec");
            return (Criteria) this;
        }

        public Criteria andUnitNameIsNull() {
            addCriterion("UNIT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUnitNameIsNotNull() {
            addCriterion("UNIT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUnitNameEqualTo(String value) {
            addCriterion("UNIT_NAME =", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotEqualTo(String value) {
            addCriterion("UNIT_NAME <>", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameGreaterThan(String value) {
            addCriterion("UNIT_NAME >", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT_NAME >=", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLessThan(String value) {
            addCriterion("UNIT_NAME <", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLessThanOrEqualTo(String value) {
            addCriterion("UNIT_NAME <=", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLike(String value) {
            addCriterion("UNIT_NAME like", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotLike(String value) {
            addCriterion("UNIT_NAME not like", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameIn(List<String> values) {
            addCriterion("UNIT_NAME in", values, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotIn(List<String> values) {
            addCriterion("UNIT_NAME not in", values, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameBetween(String value1, String value2) {
            addCriterion("UNIT_NAME between", value1, value2, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotBetween(String value1, String value2) {
            addCriterion("UNIT_NAME not between", value1, value2, "unitName");
            return (Criteria) this;
        }

        public Criteria andBasePriceIsNull() {
            addCriterion("BASE_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andBasePriceIsNotNull() {
            addCriterion("BASE_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andBasePriceEqualTo(BigDecimal value) {
            addCriterion("BASE_PRICE =", value, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceNotEqualTo(BigDecimal value) {
            addCriterion("BASE_PRICE <>", value, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceGreaterThan(BigDecimal value) {
            addCriterion("BASE_PRICE >", value, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BASE_PRICE >=", value, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceLessThan(BigDecimal value) {
            addCriterion("BASE_PRICE <", value, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BASE_PRICE <=", value, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceIn(List<BigDecimal> values) {
            addCriterion("BASE_PRICE in", values, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceNotIn(List<BigDecimal> values) {
            addCriterion("BASE_PRICE not in", values, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BASE_PRICE between", value1, value2, "basePrice");
            return (Criteria) this;
        }

        public Criteria andBasePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BASE_PRICE not between", value1, value2, "basePrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceIsNull() {
            addCriterion("PURCHASING_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceIsNotNull() {
            addCriterion("PURCHASING_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceEqualTo(BigDecimal value) {
            addCriterion("PURCHASING_PRICE =", value, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceNotEqualTo(BigDecimal value) {
            addCriterion("PURCHASING_PRICE <>", value, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceGreaterThan(BigDecimal value) {
            addCriterion("PURCHASING_PRICE >", value, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PURCHASING_PRICE >=", value, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceLessThan(BigDecimal value) {
            addCriterion("PURCHASING_PRICE <", value, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PURCHASING_PRICE <=", value, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceIn(List<BigDecimal> values) {
            addCriterion("PURCHASING_PRICE in", values, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceNotIn(List<BigDecimal> values) {
            addCriterion("PURCHASING_PRICE not in", values, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PURCHASING_PRICE between", value1, value2, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andPurchasingPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PURCHASING_PRICE not between", value1, value2, "purchasingPrice");
            return (Criteria) this;
        }

        public Criteria andProdNumIsNull() {
            addCriterion("PROD_NUM is null");
            return (Criteria) this;
        }

        public Criteria andProdNumIsNotNull() {
            addCriterion("PROD_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andProdNumEqualTo(Integer value) {
            addCriterion("PROD_NUM =", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumNotEqualTo(Integer value) {
            addCriterion("PROD_NUM <>", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumGreaterThan(Integer value) {
            addCriterion("PROD_NUM >", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROD_NUM >=", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumLessThan(Integer value) {
            addCriterion("PROD_NUM <", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumLessThanOrEqualTo(Integer value) {
            addCriterion("PROD_NUM <=", value, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumIn(List<Integer> values) {
            addCriterion("PROD_NUM in", values, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumNotIn(List<Integer> values) {
            addCriterion("PROD_NUM not in", values, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumBetween(Integer value1, Integer value2) {
            addCriterion("PROD_NUM between", value1, value2, "prodNum");
            return (Criteria) this;
        }

        public Criteria andProdNumNotBetween(Integer value1, Integer value2) {
            addCriterion("PROD_NUM not between", value1, value2, "prodNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumIsNull() {
            addCriterion("BUY_NUM is null");
            return (Criteria) this;
        }

        public Criteria andBuyNumIsNotNull() {
            addCriterion("BUY_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andBuyNumEqualTo(Integer value) {
            addCriterion("BUY_NUM =", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotEqualTo(Integer value) {
            addCriterion("BUY_NUM <>", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumGreaterThan(Integer value) {
            addCriterion("BUY_NUM >", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("BUY_NUM >=", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumLessThan(Integer value) {
            addCriterion("BUY_NUM <", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumLessThanOrEqualTo(Integer value) {
            addCriterion("BUY_NUM <=", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumIn(List<Integer> values) {
            addCriterion("BUY_NUM in", values, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotIn(List<Integer> values) {
            addCriterion("BUY_NUM not in", values, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumBetween(Integer value1, Integer value2) {
            addCriterion("BUY_NUM between", value1, value2, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotBetween(Integer value1, Integer value2) {
            addCriterion("BUY_NUM not between", value1, value2, "buyNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumIsNull() {
            addCriterion("DELIVERY_NUM is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumIsNotNull() {
            addCriterion("DELIVERY_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM =", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumNotEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM <>", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumGreaterThan(Integer value) {
            addCriterion("DELIVERY_NUM >", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM >=", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumLessThan(Integer value) {
            addCriterion("DELIVERY_NUM <", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumLessThanOrEqualTo(Integer value) {
            addCriterion("DELIVERY_NUM <=", value, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumIn(List<Integer> values) {
            addCriterion("DELIVERY_NUM in", values, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumNotIn(List<Integer> values) {
            addCriterion("DELIVERY_NUM not in", values, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumBetween(Integer value1, Integer value2) {
            addCriterion("DELIVERY_NUM between", value1, value2, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryNumNotBetween(Integer value1, Integer value2) {
            addCriterion("DELIVERY_NUM not between", value1, value2, "deliveryNum");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIsNull() {
            addCriterion("DELIVERY_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIsNotNull() {
            addCriterion("DELIVERY_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusEqualTo(Byte value) {
            addCriterion("DELIVERY_STATUS =", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotEqualTo(Byte value) {
            addCriterion("DELIVERY_STATUS <>", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusGreaterThan(Byte value) {
            addCriterion("DELIVERY_STATUS >", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("DELIVERY_STATUS >=", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusLessThan(Byte value) {
            addCriterion("DELIVERY_STATUS <", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusLessThanOrEqualTo(Byte value) {
            addCriterion("DELIVERY_STATUS <=", value, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusIn(List<Byte> values) {
            addCriterion("DELIVERY_STATUS in", values, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotIn(List<Byte> values) {
            addCriterion("DELIVERY_STATUS not in", values, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusBetween(Byte value1, Byte value2) {
            addCriterion("DELIVERY_STATUS between", value1, value2, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("DELIVERY_STATUS not between", value1, value2, "deliveryStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNull() {
            addCriterion("DELIVERY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNotNull() {
            addCriterion("DELIVERY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeEqualTo(Date value) {
            addCriterion("DELIVERY_TIME =", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotEqualTo(Date value) {
            addCriterion("DELIVERY_TIME <>", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThan(Date value) {
            addCriterion("DELIVERY_TIME >", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DELIVERY_TIME >=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThan(Date value) {
            addCriterion("DELIVERY_TIME <", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThanOrEqualTo(Date value) {
            addCriterion("DELIVERY_TIME <=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIn(List<Date> values) {
            addCriterion("DELIVERY_TIME in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotIn(List<Date> values) {
            addCriterion("DELIVERY_TIME not in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeBetween(Date value1, Date value2) {
            addCriterion("DELIVERY_TIME between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotBetween(Date value1, Date value2) {
            addCriterion("DELIVERY_TIME not between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIsNull() {
            addCriterion("SUPPLIER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIsNotNull() {
            addCriterion("SUPPLIER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierNameEqualTo(String value) {
            addCriterion("SUPPLIER_NAME =", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotEqualTo(String value) {
            addCriterion("SUPPLIER_NAME <>", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameGreaterThan(String value) {
            addCriterion("SUPPLIER_NAME >", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
            addCriterion("SUPPLIER_NAME >=", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLessThan(String value) {
            addCriterion("SUPPLIER_NAME <", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLessThanOrEqualTo(String value) {
            addCriterion("SUPPLIER_NAME <=", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLike(String value) {
            addCriterion("SUPPLIER_NAME like", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotLike(String value) {
            addCriterion("SUPPLIER_NAME not like", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIn(List<String> values) {
            addCriterion("SUPPLIER_NAME in", values, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotIn(List<String> values) {
            addCriterion("SUPPLIER_NAME not in", values, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameBetween(String value1, String value2) {
            addCriterion("SUPPLIER_NAME between", value1, value2, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotBetween(String value1, String value2) {
            addCriterion("SUPPLIER_NAME not between", value1, value2, "supplierName");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceIsNull() {
            addCriterion("REFERENCE_COST_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceIsNotNull() {
            addCriterion("REFERENCE_COST_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_COST_PRICE =", value, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceNotEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_COST_PRICE <>", value, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceGreaterThan(BigDecimal value) {
            addCriterion("REFERENCE_COST_PRICE >", value, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_COST_PRICE >=", value, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceLessThan(BigDecimal value) {
            addCriterion("REFERENCE_COST_PRICE <", value, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REFERENCE_COST_PRICE <=", value, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceIn(List<BigDecimal> values) {
            addCriterion("REFERENCE_COST_PRICE in", values, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceNotIn(List<BigDecimal> values) {
            addCriterion("REFERENCE_COST_PRICE not in", values, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REFERENCE_COST_PRICE between", value1, value2, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andReferenceCostPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REFERENCE_COST_PRICE not between", value1, value2, "referenceCostPrice");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationIsNull() {
            addCriterion("HAVE_INSTALLATION is null");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationIsNotNull() {
            addCriterion("HAVE_INSTALLATION is not null");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationEqualTo(Byte value) {
            addCriterion("HAVE_INSTALLATION =", value, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationNotEqualTo(Byte value) {
            addCriterion("HAVE_INSTALLATION <>", value, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationGreaterThan(Byte value) {
            addCriterion("HAVE_INSTALLATION >", value, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationGreaterThanOrEqualTo(Byte value) {
            addCriterion("HAVE_INSTALLATION >=", value, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationLessThan(Byte value) {
            addCriterion("HAVE_INSTALLATION <", value, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationLessThanOrEqualTo(Byte value) {
            addCriterion("HAVE_INSTALLATION <=", value, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationIn(List<Byte> values) {
            addCriterion("HAVE_INSTALLATION in", values, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationNotIn(List<Byte> values) {
            addCriterion("HAVE_INSTALLATION not in", values, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationBetween(Byte value1, Byte value2) {
            addCriterion("HAVE_INSTALLATION between", value1, value2, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andHaveInstallationNotBetween(Byte value1, Byte value2) {
            addCriterion("HAVE_INSTALLATION not between", value1, value2, "haveInstallation");
            return (Criteria) this;
        }

        public Criteria andProdCommentsIsNull() {
            addCriterion("PROD_COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andProdCommentsIsNotNull() {
            addCriterion("PROD_COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andProdCommentsEqualTo(String value) {
            addCriterion("PROD_COMMENTS =", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsNotEqualTo(String value) {
            addCriterion("PROD_COMMENTS <>", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsGreaterThan(String value) {
            addCriterion("PROD_COMMENTS >", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("PROD_COMMENTS >=", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsLessThan(String value) {
            addCriterion("PROD_COMMENTS <", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsLessThanOrEqualTo(String value) {
            addCriterion("PROD_COMMENTS <=", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsLike(String value) {
            addCriterion("PROD_COMMENTS like", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsNotLike(String value) {
            addCriterion("PROD_COMMENTS not like", value, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsIn(List<String> values) {
            addCriterion("PROD_COMMENTS in", values, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsNotIn(List<String> values) {
            addCriterion("PROD_COMMENTS not in", values, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsBetween(String value1, String value2) {
            addCriterion("PROD_COMMENTS between", value1, value2, "prodComments");
            return (Criteria) this;
        }

        public Criteria andProdCommentsNotBetween(String value1, String value2) {
            addCriterion("PROD_COMMENTS not between", value1, value2, "prodComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsIsNull() {
            addCriterion("INSIDE_COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsIsNotNull() {
            addCriterion("INSIDE_COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsEqualTo(String value) {
            addCriterion("INSIDE_COMMENTS =", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsNotEqualTo(String value) {
            addCriterion("INSIDE_COMMENTS <>", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsGreaterThan(String value) {
            addCriterion("INSIDE_COMMENTS >", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("INSIDE_COMMENTS >=", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsLessThan(String value) {
            addCriterion("INSIDE_COMMENTS <", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsLessThanOrEqualTo(String value) {
            addCriterion("INSIDE_COMMENTS <=", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsLike(String value) {
            addCriterion("INSIDE_COMMENTS like", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsNotLike(String value) {
            addCriterion("INSIDE_COMMENTS not like", value, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsIn(List<String> values) {
            addCriterion("INSIDE_COMMENTS in", values, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsNotIn(List<String> values) {
            addCriterion("INSIDE_COMMENTS not in", values, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsBetween(String value1, String value2) {
            addCriterion("INSIDE_COMMENTS between", value1, value2, "insideComments");
            return (Criteria) this;
        }

        public Criteria andInsideCommentsNotBetween(String value1, String value2) {
            addCriterion("INSIDE_COMMENTS not between", value1, value2, "insideComments");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdIsNull() {
            addCriterion("ARRIVAL_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdIsNotNull() {
            addCriterion("ARRIVAL_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdEqualTo(Integer value) {
            addCriterion("ARRIVAL_USER_ID =", value, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdNotEqualTo(Integer value) {
            addCriterion("ARRIVAL_USER_ID <>", value, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdGreaterThan(Integer value) {
            addCriterion("ARRIVAL_USER_ID >", value, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ARRIVAL_USER_ID >=", value, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdLessThan(Integer value) {
            addCriterion("ARRIVAL_USER_ID <", value, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("ARRIVAL_USER_ID <=", value, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdIn(List<Integer> values) {
            addCriterion("ARRIVAL_USER_ID in", values, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdNotIn(List<Integer> values) {
            addCriterion("ARRIVAL_USER_ID not in", values, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdBetween(Integer value1, Integer value2) {
            addCriterion("ARRIVAL_USER_ID between", value1, value2, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ARRIVAL_USER_ID not between", value1, value2, "arrivalUserId");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusIsNull() {
            addCriterion("ARRIVAL_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusIsNotNull() {
            addCriterion("ARRIVAL_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusEqualTo(Byte value) {
            addCriterion("ARRIVAL_STATUS =", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusNotEqualTo(Byte value) {
            addCriterion("ARRIVAL_STATUS <>", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusGreaterThan(Byte value) {
            addCriterion("ARRIVAL_STATUS >", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("ARRIVAL_STATUS >=", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusLessThan(Byte value) {
            addCriterion("ARRIVAL_STATUS <", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusLessThanOrEqualTo(Byte value) {
            addCriterion("ARRIVAL_STATUS <=", value, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusIn(List<Byte> values) {
            addCriterion("ARRIVAL_STATUS in", values, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusNotIn(List<Byte> values) {
            addCriterion("ARRIVAL_STATUS not in", values, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusBetween(Byte value1, Byte value2) {
            addCriterion("ARRIVAL_STATUS between", value1, value2, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("ARRIVAL_STATUS not between", value1, value2, "arrivalStatus");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNull() {
            addCriterion("ARRIVAL_TIME is null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNotNull() {
            addCriterion("ARRIVAL_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME =", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME <>", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThan(Date value) {
            addCriterion("ARRIVAL_TIME >", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME >=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThan(Date value) {
            addCriterion("ARRIVAL_TIME <", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThanOrEqualTo(Date value) {
            addCriterion("ARRIVAL_TIME <=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIn(List<Date> values) {
            addCriterion("ARRIVAL_TIME in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotIn(List<Date> values) {
            addCriterion("ARRIVAL_TIME not in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeBetween(Date value1, Date value2) {
            addCriterion("ARRIVAL_TIME between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotBetween(Date value1, Date value2) {
            addCriterion("ARRIVAL_TIME not between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreIsNull() {
            addCriterion("IS_IGNORE is null");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreIsNotNull() {
            addCriterion("IS_IGNORE is not null");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreEqualTo(Byte value) {
            addCriterion("IS_IGNORE =", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotEqualTo(Byte value) {
            addCriterion("IS_IGNORE <>", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreGreaterThan(Byte value) {
            addCriterion("IS_IGNORE >", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreGreaterThanOrEqualTo(Byte value) {
            addCriterion("IS_IGNORE >=", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreLessThan(Byte value) {
            addCriterion("IS_IGNORE <", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreLessThanOrEqualTo(Byte value) {
            addCriterion("IS_IGNORE <=", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreIn(List<Byte> values) {
            addCriterion("IS_IGNORE in", values, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotIn(List<Byte> values) {
            addCriterion("IS_IGNORE not in", values, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreBetween(Byte value1, Byte value2) {
            addCriterion("IS_IGNORE between", value1, value2, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotBetween(Byte value1, Byte value2) {
            addCriterion("IS_IGNORE not between", value1, value2, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeIsNull() {
            addCriterion("IGNORE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeIsNotNull() {
            addCriterion("IGNORE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeEqualTo(Long value) {
            addCriterion("IGNORE_TIME =", value, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeNotEqualTo(Long value) {
            addCriterion("IGNORE_TIME <>", value, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeGreaterThan(Long value) {
            addCriterion("IGNORE_TIME >", value, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("IGNORE_TIME >=", value, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeLessThan(Long value) {
            addCriterion("IGNORE_TIME <", value, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeLessThanOrEqualTo(Long value) {
            addCriterion("IGNORE_TIME <=", value, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeIn(List<Long> values) {
            addCriterion("IGNORE_TIME in", values, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeNotIn(List<Long> values) {
            addCriterion("IGNORE_TIME not in", values, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeBetween(Long value1, Long value2) {
            addCriterion("IGNORE_TIME between", value1, value2, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreTimeNotBetween(Long value1, Long value2) {
            addCriterion("IGNORE_TIME not between", value1, value2, "ignoreTime");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdIsNull() {
            addCriterion("IGNORE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdIsNotNull() {
            addCriterion("IGNORE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdEqualTo(Integer value) {
            addCriterion("IGNORE_USER_ID =", value, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdNotEqualTo(Integer value) {
            addCriterion("IGNORE_USER_ID <>", value, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdGreaterThan(Integer value) {
            addCriterion("IGNORE_USER_ID >", value, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("IGNORE_USER_ID >=", value, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdLessThan(Integer value) {
            addCriterion("IGNORE_USER_ID <", value, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("IGNORE_USER_ID <=", value, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdIn(List<Integer> values) {
            addCriterion("IGNORE_USER_ID in", values, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdNotIn(List<Integer> values) {
            addCriterion("IGNORE_USER_ID not in", values, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdBetween(Integer value1, Integer value2) {
            addCriterion("IGNORE_USER_ID between", value1, value2, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andIgnoreUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("IGNORE_USER_ID not between", value1, value2, "ignoreUserId");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("ADD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("ADD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("ADD_TIME =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("ADD_TIME <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("ADD_TIME >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("ADD_TIME <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("ADD_TIME <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("ADD_TIME in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("ADD_TIME not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("ADD_TIME not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddIdIsNull() {
            addCriterion("ADD_ID is null");
            return (Criteria) this;
        }

        public Criteria andAddIdIsNotNull() {
            addCriterion("ADD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAddIdEqualTo(Long value) {
            addCriterion("ADD_ID =", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdNotEqualTo(Long value) {
            addCriterion("ADD_ID <>", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdGreaterThan(Long value) {
            addCriterion("ADD_ID >", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ADD_ID >=", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdLessThan(Long value) {
            addCriterion("ADD_ID <", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdLessThanOrEqualTo(Long value) {
            addCriterion("ADD_ID <=", value, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdIn(List<Long> values) {
            addCriterion("ADD_ID in", values, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdNotIn(List<Long> values) {
            addCriterion("ADD_ID not in", values, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdBetween(Long value1, Long value2) {
            addCriterion("ADD_ID between", value1, value2, "addId");
            return (Criteria) this;
        }

        public Criteria andAddIdNotBetween(Long value1, Long value2) {
            addCriterion("ADD_ID not between", value1, value2, "addId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(Long value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(Long value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(Long value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(Long value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(Long value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<Long> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<Long> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(Long value1, Long value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(Long value1, Long value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 16 14:44:45 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SALEORDER_GOODS
     *
     * @mbg.generated Mon Sep 16 14:44:45 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}