package top.ezadmin.domain.model;

import java.util.Date;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String addName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.PARENT_ROLE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Long parentRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_DESC
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_WEIGHT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    private Integer roleWeight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_ID
     *
     * @return the value of T_SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_ID
     *
     * @param roleId the value for T_SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.COMPANY_ID
     *
     * @return the value of T_SYS_ROLE.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.COMPANY_ID
     *
     * @param companyId the value for T_SYS_ROLE.COMPANY_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_NAME
     *
     * @return the value of T_SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ADD_TIME
     *
     * @return the value of T_SYS_ROLE.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ADD_TIME
     *
     * @param addTime the value for T_SYS_ROLE.ADD_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ADD_ID
     *
     * @return the value of T_SYS_ROLE.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ADD_ID
     *
     * @param addId the value for T_SYS_ROLE.ADD_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ADD_NAME
     *
     * @return the value of T_SYS_ROLE.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ADD_NAME
     *
     * @param addName the value for T_SYS_ROLE.ADD_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.UPDATE_TIME
     *
     * @return the value of T_SYS_ROLE.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.UPDATE_TIME
     *
     * @param updateTime the value for T_SYS_ROLE.UPDATE_TIME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.UPDATE_ID
     *
     * @return the value of T_SYS_ROLE.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.UPDATE_ID
     *
     * @param updateId the value for T_SYS_ROLE.UPDATE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.UPDATE_NAME
     *
     * @return the value of T_SYS_ROLE.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.UPDATE_NAME
     *
     * @param updateName the value for T_SYS_ROLE.UPDATE_NAME
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.DELETE_FLAG
     *
     * @return the value of T_SYS_ROLE.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.DELETE_FLAG
     *
     * @param deleteFlag the value for T_SYS_ROLE.DELETE_FLAG
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.PARENT_ROLE_ID
     *
     * @return the value of T_SYS_ROLE.PARENT_ROLE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Long getParentRoleId() {
        return parentRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.PARENT_ROLE_ID
     *
     * @param parentRoleId the value for T_SYS_ROLE.PARENT_ROLE_ID
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setParentRoleId(Long parentRoleId) {
        this.parentRoleId = parentRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_DESC
     *
     * @return the value of T_SYS_ROLE.ROLE_DESC
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_DESC
     *
     * @param roleDesc the value for T_SYS_ROLE.ROLE_DESC
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_WEIGHT
     *
     * @return the value of T_SYS_ROLE.ROLE_WEIGHT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public Integer getRoleWeight() {
        return roleWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_WEIGHT
     *
     * @param roleWeight the value for T_SYS_ROLE.ROLE_WEIGHT
     *
     * @mbg.generated Fri Dec 27 21:36:51 CST 2024
     */
    public void setRoleWeight(Integer roleWeight) {
        this.roleWeight = roleWeight;
    }
}